name: run-tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:  ["3.11", "3.10", "3.9", "3.8", "3.7",]

    steps:
      - name: Chckout code
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install tshark
          python -m pip install --upgrade pip
          pip install pytest
          pip install -e ./src/

      - name: Test with pytest
        run: |
          python -m pytest -v
